services:
  omdb-adapter:
    build:
      context: ./adapter_services/omdb_adapter
    container_name: omdb-adapter
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - OMDB_API_KEY=${OMDB_API_KEY}
    volumes:
      - ./adapter_services/omdb_adapter:/omdb_adapter 
  
  streaming-availability-adapter:
    build:
      context: ./adapter_services/streaming_availability_adapter
    container_name: streaming-availability-adapter
    ports:
      - "5002:5000"
    env_file:
      - .env
    environment:
      - STREAMING_AVAILABILITY_API_KEY=${STREAMING_AVAILABILITY_API_KEY}
    volumes:
      - ./adapter_services/streaming_availability_adapter:/streaming_availability_adapter 
    
  tmdb-adapter:
    build:
      context: ./adapter_services/tmdb_adapter
    container_name: tmdb-adapter
    ports:
      - "5003:5000"
    env_file:
      - .env
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
    - ./adapter_services/tmdb_adapter:/tmdb_adapter 
     
  spotify-adapter:
    build:
      context: ./adapter_services/spotify_adapter
    container_name: spotify-adapter
    ports:
      - "5004:5000"
    env_file:
      - .env
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./adapter_services/spotify_adapter:/spotify_adapter 

  movie-details-interface:
    build:
      context: ./frontend/movie_details
    container_name: movie-details-interface
    ports:
      - "5006:5000"
    env_file:
      - .env
    volumes:
      - ./frontend/movie_details:/movie_details

  groq-adapter:
    build:
      context: ./adapter_services/groq_adapter
    container_name: groq-adapter
    ports:
      - "5007:5000"
    env_file:
      - .env
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./adapter_services/groq_adapter:/groq_adapter

  youtube-adapter:
    build:
      context: ./adapter_services/youtube_adapter
    container_name: youtube-adapter
    ports:
      - "5009:5000"
    env_file:
      - .env
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    volumes:
      - ./adapter_services/youtube_adapter:/youtube_adapter

  user-db-adapter:
    build:
      context: ./adapter_services/user_db_adapter
    container_name: user-db-adapter
    ports:
      - "5010:5000"
    env_file:
      - .env
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - DB_NAME=${DB_NAME}

  email-check-adapter:
    build:
      context: ./adapter_services/email_check_adapter
    container_name: email-check-adapter
    ports:
      - "5011:5000"
    env_file:
      - .env
    environment:
      - ABSTRACT_API_KEY=${ABSTRACT_API_KEY}

  valid-email-service:
    build:
      context: ./business_logic_services/valid_email_service
    container_name: valid-email-service
    ports:
      - "5012:5000"
    depends_on:
      - email-check-adapter

  user-registration-service:
    build:
      context: ./process_centric_services/user_registration_service
    container_name: user-registration-service
    ports:
      - "5013:5000"
    depends_on:
      - valid-email-service
      - user-db-adapter
  
  user-login-service:
    build:
      context: ./process_centric_services/user_login_service
    container_name: user-login-service
    ports:
      - "5014:5000"
    depends_on:
      - user-db-adapter
    env_file:
      - .env

volumes:
  movie-match: