# Services grouped by type
services:
# Internal PostregSQL DB
  postgres-db:
    image: postgres:18-alpine
    container_name: postgres_container
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  movie-core:
    build:
      context: ./movie-core/
    container_name: movie-core
    ports:
      - "5019:5000"
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - ./movie-core:/movie-core

  recommendation-svc:
    build:
      context: ./recommendation-svc/
    container_name: recommendation-svc
    ports:
      - "5020:5000"
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./recommendation-svc:/recommendation-svc
    depends_on:
      postgres-db:
        condition: service_healthy


  seeder:
    build: ./recommendation-svc
    command: python seed.py
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      postgres-db:
        condition: service_healthy
      movie-core:
        condition: service_started

  # Frontend Services
  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    ports:
      - "80:5000"
    volumes:
      - ./frontend:/frontend

# Networks
networks:
  movie-match-network:
    name: movie-match-network
    driver: bridge

# Volumes
volumes:
  movie-match:
    name: movie-match-data
  pg_data:

