version: '3.8'

services:
  omdb-adapter:
    build:
      context: ./adapter_services/omdb_adapter
    container_name: omdb-adapter
    ports:
      - "5001:5000"
    env_file:
      - .env
    environment:
      - OMDB_API_KEY=${OMDB_API_KEY}
    
  streaming-availability-adapter:
    build:
      context: ./adapter_services/streaming_availability_adapter
    container_name: streaming-availability-adapter
    ports:
      - "5002:5000"
    env_file:
      - .env
    environment:
      - STREAMING_AVAILABILITY_API_KEY=${STREAMING_AVAILABILITY_API_KEY}
    
  tmdb-adapter:
    build:
      context: ./adapter_services/tmdb_adapter
    container_name: tmdb-adapter
    ports:
      - "5003:5000"
    env_file:
      - .env
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
  
  user-db-adapter:
    build:
      context: ./adapter_services/user_db_adapter
    container_name: user-db-adapter
    ports:
      - "5008:5000"
    env_file:
      - .env
    environment:
      - ATLAS_URI=${ATLAS_URI}
      - DB_NAME=${DB_NAME}

volumes:
  mongo-data: